"""updatess

Revision ID: 5d4896004be3
Revises: ed417a368c0b
Create Date: 2024-06-04 20:27:48.416449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4896004be3'
down_revision: Union[str, None] = 'ed417a368c0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inputs', 'city_pop',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inputs', 'city_pop',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
